### ISSUE TITLE
video still playing after clicking on previous story 

### ISSUE THREAD

**Issue by samih93** [AdnanKhan45/flutter-story-view#1]

**Comment by samih93** [comment]
fixed after adding _videoController!.pause(); in onprevious  function

**Comment by AdnanKhan45** [comment]
Yes the video will still plays if you tap previous and the current story item is first, functionality of closing the story if the current story item is first will be added in the next version.

**Comment by samih93** [comment]
Bro why do not add all fields needed in storyitem , like caption , like date , i already updated it locally
To avoid changing the state of current index , but it perfect bro thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdnanKhan45** [comment]
It like real WhatsApp the caption just shows up only on first story and the date uploaded is same for all of the uploaded stories that is why it's not included in the StoryItem. But, we will improve it by adding more features and adding the capabilites that you suggest Thanks you for your interest in the package :)
