### ISSUE TITLE
Progress bar to match the video legnth? 

### ISSUE THREAD

**Issue by flirtyapp** [AdnanKhan45/flutter-story-view#3]
Hi, 

I'm just wondering how I can get the progress bar to match the video length? I know we can set a duration but each video will be different. 

Thank you.

**Comment by AdnanKhan45** [comment]
You can just pass video type to your video in StoryItem and the package will manage the rest for you. You don't need to explicitly tell the package what to do but instead the package is smart enough to do this job for you. I'm closing this issue for now and if you have any other issues related, so you can open it again with a detailed description. Thank you.
