### ISSUE TITLE
userInfo may be null

### ISSUE THREAD

**Issue by berkaycatak** [AdnanKhan45/flutter-story-view#4]
Error occurs when userInfo is not sent. When an empty object is sent, a demo user appears.

<img width="882" alt="Ekran Resmi 2023-10-12 15 45 56" src="https://github.com/AdnanKhan45/flutter-story-view/assets/34205493/2c458a1d-985a-4f2e-b69d-b48e923c8560">

**Comment by AdnanKhan45** [comment]
I review the changes on your PR, please confirm that changes so that I can merge your PR. I'm closing this issue if there's any other you can create it again. Thank you for your contribution.
